---
title: "Générateurs de scénarios économiques"
author: "Mehdi KAIROUN, William LAURENT, Oskar LAVERNY, Pierre MARJOLLET"
header-includes:
  - \usepackage[francais]{babel}
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\tableofcontents


#I. Mise en place du framework

## Sujet et cadre d'étude

Ce projet de groupe est effectué dans le cadre du cours de *Générateurs de scénarios économiques* - **GSE** dispensé à l'ISFA. La trame que nous allons suivre est la suivante :

* Création d'un GSE "mono indice" risque neutre
* Calcul de *Best Estimate* - **BE** empirique dans le cadre d'un contrat d'épargne en *Unité de Compte* - **UC**
* Etude de la sensibilité induite par le calibrage du modèle séléctionné

## Nos outils

Pour mener à bien ce projet, nous alons exploiter le langage open-source **R** muni des librairies suivantes :

* **ESG** - librairie co-produite en 2013 par Frédérique PLANCHET, enseignant et chercheur de l'ISFA. Elle offre une procédure pour valoriser plusieurs produits d'assurance (type épargne, retraite, ...)
* **RMarkdown** - librairie proposé par les fondateurs de RStudio, Au vue de proposer des rendus PDF de code, elle compile le code écrits et comprends le language *LaTeX*. Le rendu de ce projet a été produit par RMarkdown.
* **magrittr** - librairie incoutournable. Elle propose de performants opérateurs très plébiscité par les utilisateurs de R pour gagner en lisibilité de code

#II. Création d'un GSE mono-indice

## Paramètres de la modélisation

Les paramètres que nous avons retenues pour la simulation sont les suivants:

* horizon $T=5$ années 
* valeure initiale de l'action $S(0)=100$
* nombre de scénario $n=10\,000$


## Courbe de taux zéros coupons

### Réglementation

Sous Solvabilité II, le régulateur publie mensuellement des courbes de taux zéro coupons. Ces courbes servent à actualiser les engagements de l'assureur en simulant des prix d'actifs dans le monde risque neutre. Le régulateur indique également que la publication de courbe de taux permets d'harmoniser et d'auditer les calculs des provisions.

### Méthodologie

Quelques brefs mots sur la méthodologie qu'utilise EIOPA pour dresser une courbe de taux 

### Courbe choisie

En annexe vous trouverez la courbe gardée___

## Choix du modèle

Nous avons profité des modèles déjà implémentés dans la librairie GSE. Nous vous présentons la modélisation retenue ainsi que les paramètres initiaux de la simulation.

Dans la suite, on retiendra les notations suivantes :

* $P(t,T), \forall t \,/\, 1 \le t \le T$, la valeur du zéro coupon actualisé en t
* $R(t,T) = - \frac{log(P(t,T))}{T-t}$ le taux spot continu en t, d'échéance T
* $f(t,T) = \lim\limits_{S \leftarrow T_+}F(t; T, S) := - \frac{d\,logP(t,T)}{d\,T}$ le taux forward instantanné en t, d'échéance T.
* $(r_t = \lim_{T \leftarrow t_+}f(t,T), t \ge 0)$ le taux court en t.

L'unique input de notre modélisation est la courbe de courbe de zéro coupons donnée par le régulateur. Dans la suite de l'exposé, les parmaètres de modélisation ont été séléctionné par dire d'experts.

### Modèle de taux courts

Nous modélisons les taux forward instantanés $f$ par *Heath-Jarrow-Merton* - HJM. On a
$$df(t,T) = \mu(t,T)dt + \sigma(t,T)dW_t$$
Ce HJM nous permettra, une fois $f(t,T)$ calculé, de passer à la limite pour enfin déduire le taux court $r_t$.

En $mathématiques financières$ on a vue qu'une unique mesure martingale en absence d'opportunité d'arbitrage induit
$$\mu(t,T)dt = \sigma(t,T) \int\limits_t^T\sigma(t,s)ds$$
Le drift étant une fonction de la volatilité, cela nous simplifie le modèle.

Enfin, la structure de volatilité des taux forward est induite par une caractérisation type Hull & White - Vasicek généralisé. On choisit
$$\sigma(t,T):=\sigma e^{-k(t-T)}$$
Dans ce projet $k=2$ et $\sigma=0,1$

Nous avons maintenant des valeurs de taux courts et des structures de volatilité des taux forward. Construisons nos actifs sur cette base.

### Modélisation des actifs

On modélise les actions par une formule de Black-Scholes à l'aide du taux court simulé plus haut 
$$\frac{dS_t}{S_t} = r_tdt + \sigma_{bs}(\rho dW_t^1 + \sqrt{1-\rho ^2}dW_t^2)$$
Ici $\rho$ représente la corrélation entre l'action et le taux d'intérêt, modélisés par $(W_t)_t^i,i=1,2$, mouvements browniens standard en monde risque-neutre.

Nous avons gardé une corrélation positive $\rho = 0.5$, et la volatilité constante $\sigma_bs = 0.2$

## Test de martingalité

Enfin, pour nous assuré de la cohérence de nos modélisations, nous vérifions que les actifs actualisés issus de notre modélisation sont bien des martingales. On se retrouve 

#III. Analyse et application à un contrat d'épargne en UC

## Contrat et résultat fondamental

### Le contrat d'épargne en UC

Lors du cours de *Modèles financiers en assurance* donné par M. PLANCHET, nous avons exprimé la valeur théorique du BE d'un contrat d'épargne en UC. Posons le cadre :

* Sous-jacent : $(S(t), t\ge0)$
* Investissement initial $S(0)$
* Durée du contrat $T$
* Rachat en $\tau$ permis n'importe quand de fréquence constante
* Pas de prorogation $(\tau \le T)$ - *A terme, le contrat est rachêté*

On définit $\Lambda \, := \sum\limits_{t=1}^{T}\delta(t)F(t)$, $\Lambda$ la somme des engagements actualisés de l'assureur avec

* $\delta(t) \, := e^{-\int\limits_{0}^{t}r_u\,du}$ le *discount factor*, $(r_u, u\ge0)$ le taux court
* $F$ les flux représentents les engagements de l'assureur

### Valeur du BE dans un contrat d'épargne en UC

On calcul le best estimate avec $BE = \mathbb{E}^{\mathbb{P}\times\mathbb{Q}}(\Lambda)$ avec

* $\mathbb{P}$ la probabilité historique de l'assureur
* $\mathbb{Q}$ la probabilité risque neutre

En indiquant que $\tau$ peut également être le rachat des héritiers au décés de l'assuré, on a $F(t)=S(t) \mathbb{1}_{\tau=t}$. On note que dans le cas général $\mathbb{1}_{\tau=t}$ dépends des probabilités $\mathbb{Q}$ et $\mathbb{P}$ alors

$$BE = \sum\limits_{t=1}^{T}\mathbb{E}^{\mathbb{P}\times\mathbb{Q}}(\delta(t) S(t) \mathbb{1}_{\tau=t})$$

En notant $\mathcal{F}_t$ l'information financière disponnible en $t$. On a alors
$$BE = \sum\limits_{t=1}^{T}\mathbb{E}^{\mathbb{Q}}(\delta(t) S(t) \mathbb{E}^{\mathbb{P}}(\mathbb{1}_{\tau=t} | \mathcal{F}_t))$$

En notant $q_t := \mathbb{E}^{\mathbb{P}}(\mathbb{1}_{\tau=t} | \mathcal{F}_t)$ la probabilité de rachat, il vient 
$$BE = \sum\limits_{t=1}^{T}\mathbb{E}^{\mathbb{Q}}(\delta(t) S(t) q_t)$$

Comme les taux de rachat sont constants, le calcul de $q_t$ ne dépends ni de l'information financière, ni de la probabilité historique de l'assureur

$$BE = \sum\limits_{t=1}^{T} q_t\mathbb{E}^{\mathbb{Q}}(\delta(t) S(t))$$

Comme dans le monde risque neutre $(\delta(t)S(t), t \ge 1)$ est une martingale sous $\mathbb{Q}$

$$BE=S(0) \sum\limits_{t=1}^{T} q_t$$

Finalement

$$BE=S(0)$$
**En cours, nous avons également démontré que ce résultat reste vrai si les rachats ne sont pas constants**. Ce résultat fondamental va diriger nos études et nous permettre d'être conforté dans les valeurs prisent par le BE empirique par monté carlo.

## Calcul du BE empirique

Définissons le BE empirique pour $n$ simulations :

$$\widehat{BE}_n \, := \frac{1}{n}  \sum\limits_{k=1}^{n} \sum\limits_{t=1}^{T} \delta^{(k)}(t)F^{(k)}(t)$$

* $\delta^{(k)}(t)$ la $k^{ième}$ simulation du facteur d'actualisation en $t$
* $F^{(k)}(t)$ la $k^{ième}$ simulation de l'engagement de l'assureur en $t$

Enfin

$$BE = \lim\limits_{n \rightarrow \infty} \widehat{BE}_n$$
## Résultats et temps de convergence
## Tests de sensibilités





http://www.ressources-actuarielles.net/EXT/ISFA/fp-isfa.nsf/34a14c286dfb0903c1256ffd00502d73/a5e99e9abf5d3674c125772f00600f6c/$FILE/ESG.pdf
